export class RepeatError extends Error {}
export class ConcatError extends Error {}
export class EvaluationError extends Error {}
export class ExtensionError extends Error {}
export class MultiDriverConflictError extends Error {}
export class SignalOwnershipError extends Error {}
export class SignalWidthError extends Error {}
export class SliceError extends Error {}
export class SwitchError extends Error {}
export class SubmoduleError extends Error {}
export class SimulationModuleError extends Error {}
export class UndrivenSignalError extends Error {}
export class ValidNumericTypeError extends Error {}
export class MissingPortError extends Error {}
export class VendorSignalError extends Error {}
export class ChildModuleError extends Error {}
export class BidirectionalSignalError extends Error {}
